### ISSUE TITLE
compile in ubuntu 14.04?

### ISSUE THREAD

**Issue by Asta1986** [xyzz/acquisition#327]
Hello, first of all thanks for your work, I really like acquisition, but I'm not being able to compile it on my ubuntu 14.04 system, I'm getting all sorts of errors about missing modules (like qtwidgets, qtgui) when running make or trying to build it with qtcreator.
Any suggestions?

**Comment by xyzz** [comment]
At least Qt 5.5 is required.

**Comment by Asta1986** [comment]
Thanks for the info. I've downloaded qt 5.6 from the website and when trying to build the program with qt creator now I get the following error:
/home/asta666/Desktop/acquisition-0.5f/src/itemsmanagerworker.cpp:391: error: no matching function for call to 'QTimer::singleShot(int, ItemsManagerWorker::OnTabReceived(int)::__lambda0)'
             QTimer::singleShot(1, [&]() { FetchItems(cached_requests_completed_); });
                                                                                    ^

**Comment by ericsium** [comment]
I don't think anyone has attempted to compile with qt 5.6 on linux up to this point.  If you want to make sure you're toolset is as close as possible to what aquisition is tested with check out .travis.yml in the root of the repo.  Currently tested with precise, using QT 5.4.2 and you'll definitely need at least GCC 4.9 or clang 3.6.

**Comment by ericsium** [comment]
Just as a followup, I believe the reason for this is [these changes to QTimer](https://fossies.org/diffs/qt-everywhere-opensource-src/5.5.1_vs_5.6.0/qtbase/src/corelib/kernel/qtimer.h-diff.html) from 5.5.x to 5.6.0.

The typedef is not only enabled under certain conditions and it doesn't like my lambda anymore for some reason.

You're going to have other issues with 5.6, QT Webkit is deprecated etc... so I'd try 5.4.2 to be on the safe side.

**Comment by Asta1986** [comment]
I tried with 5.5 and 5.4.2 and received the same error.

**Comment by ericsium** [comment]
For install did you possibly miss any steps as listed in [this video](https://www.youtube.com/watch?v=to1qlTUbQ-w).  Can you run example QT projects succesfully?

Do you have at least GCC 4.9?  I think 4.8.2 is default on trusty.

**Comment by Gloorf** [comment]
I haven't tried on ubuntu trusty, but on a fresh debian all you need to install is : 
`apt-get install qt5-qmake qtcreator liberror-perl git g++ qt5(default libqt5qtwebkit5-dev`
After that, you should be able to ismply open qtcreator, open the .pro file, and build.
Make sure you have GCC 4.9 as ericsium pointed, or else it won't work.

**Comment by Asta1986** [comment]
Yeah I guess the GCC version is causing the problem. Could someone perhaps give me some tips in order to compile it using clang 3.6? That one is in the default trusty repos, if possible I'd like to avoid adding another ppa to install GCC 4.9.
I installed clang 3.6 but qtcreator is not detecting it automatically in the compiler list, and I've not been able to set it manually correctly.

**Comment by Gloorf** [comment]
Make sure you have installed the clang package and not just the clang-3.6 (it's needed by qtcreator to automatically detect it), and to restart QtCreator after you installed it.

If it doesn't work, you can add it manually by going tools > options > Build & Run > Compilers > Add > Clang, and put /usr/bin/clang++ as compiler path (or wherever your clang executable is located).
After that, clone your "Desktop" kit (or whatever it's named, the one with gcc), and just change the compiler to Clang instead of gcc.

**Comment by Asta1986** [comment]
I tried manually setting the clang++ path but even then it doesn't accept it (error about compiler not being able to produce code for the available qt versions). I think I've installed all of the clang packages including recommends.
I also tried gcc 4.9 (/usr/bin/g++-4.9, qt 5.5.1) and got this in qt creator:
/home/asta666/Desktop/acquisition-0.5f/src/util.cpp:37: error: boost/algorithm/string/join.hpp: No such file or directory
 #include <boost/algorithm/string/join.hpp>
                                           ^

**Comment by ericsium** [comment]
You need to check out the projects submodules:

git submodule update --init deps/boost-header-only
